### ISSUE TITLE
Improvements todo

### ISSUE THREAD

**Issue by xen-42** [xen-42/ow-mod-jam-3-base#6]
- [x] Make sun shine on first place
- [x] Add details around the placing whiteboards with more details for higher places
- [x] Fix typo on "thrid" place
- [x] Turn ship to face system
